[build]
  # No build command needed for static site
  command = ""
  
  # Publish directory (root of the project)
  publish = "."

[build.environment]
  # Node version (if needed for any future build processes)
  NODE_VERSION = "18"

# Custom headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

# Specific cache rules for different file types
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules (if needed)
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# 404 page fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200